security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Participant:
            algorithm: plaintext
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
    # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Participant # classe d'utilisateurs (elle peut avoir un autre nom que User)

                property: login # propriété de la classe d'utilisateurs qui joue le rôle de login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                # "login" is the name of the route created previously
                login_path: connexionParticipant
                check_path: connexionParticipant
            logout:
                path: security_logout
                    # La route sur laquelle doit être redirigé l'utilisateur après une déconnexion
                target: http://localhost:8000/
 
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
